/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed": "#2d0050",
        "surface-container-highest": "#353535",
        "primary-fixed": "#ceef7f",
        "on-surface": "#e5e2e1",
        "background": "#131313",
        "focus-purple": "#BC84EE",
        "tertiary-fixed-dim": "#e5bfa8",
        "on-tertiary": "#432b1b",
        "on-surface-variant": "#c5c8b4",
        "on-error-container": "#ffdad6",
        "surface-container": "#20201f",
        "surface-raised": "#262626",
        "on-secondary-fixed-variant": "#612b90",
        "on-primary-fixed": "#151f00",
        "secondary-fixed-dim": "#deb7ff",
        "on-error": "#690005",
        "primary": "#ffffff",
        "primary-container": "#ceef7f",
        "on-secondary": "#490b78",
        "inverse-surface": "#e5e2e1",
        "tertiary-fixed": "#ffdcc7",
        "surface-tint": "#b3d266",
        "on-primary": "#273500",
        "surface-container-low": "#1c1b1b",
        "surface-container-high": "#2a2a2a",
        "secondary-fixed": "#f1dbff",
        "on-background": "#e5e2e1",
        "on-secondary-container": "#d5a4ff",
        "surface": "#131313",
        "error-container": "#93000a",
        "surface-container-lowest": "#0e0e0e",
        "outline-variant": "#454839",
        "surface-bright": "#393939",
        "success-lime": "#DCFD8B",
        "on-primary-fixed-variant": "#3a4d00",
        "warm-peach": "#FDD5BD",
        "tertiary": "#ffffff",
        "secondary-container": "#632d93",
        "on-tertiary-fixed-variant": "#5c412f",
        "inverse-primary": "#4e6700",
        "surface-variant": "#353535",
        "secondary": "#deb7ff",
        "surface-dim": "#131313",
        "on-tertiary-fixed": "#2b1708",
        "tertiary-container": "#ffdcc7",
        "error": "#ffb4ab",
        "primary-fixed-dim": "#b3d266",
        "on-tertiary-container": "#7c5e4b",
        "on-primary-container": "#536d05",
        "background-deep": "#0F0F0F",
        "outline": "#8f9380",
        "inverse-on-surface": "#313030"
      },
      borderRadius: {
        "DEFAULT": "1rem",
        "lg": "2rem",
        "xl": "3rem",
        "full": "9999px"
      },
      spacing: {
        "gutter": "16px",
        "max-width": "1200px",
        "margin-mobile": "20px",
        "margin-desktop": "48px",
        "base-unit": "8px"
      },
      fontFamily: {
        "headline-lg-mobile": ["Comfortaa"],
        "body-sm": ["Quicksand"],
        "body-lg": ["Quicksand"],
        "headline-xl": ["Comfortaa"],
        "headline-lg": ["Comfortaa"],
        "label-md": ["Quicksand"],
        "label-lg": ["Quicksand"],
        "headline-md": ["Comfortaa"],
        "body-md": ["Quicksand"]
      },
      fontSize: {
        "headline-lg-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "28px", "fontWeight": "500" }],
        "headline-xl": ["40px", { "lineHeight": "48px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "fontWeight": "700" }],
        "label-md": ["12px", { "lineHeight": "14px", "fontWeight": "600" }],
        "label-lg": ["14px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "headline-md": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "24px", "fontWeight": "500" }]
      }
    },
  },
  plugins: [],
}
